# Generated by Django 4.2.2 on 2023-06-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
                ('comuna', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
                ('servicios', models.CharField(max_length=15)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
