# Generated by Django 4.2 on 2023-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayoMakween', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
